# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24affddd322c7ea4e276ab76540d9d68af69b7d8dc599c01897f3e5e5f414fae59eb5388f044881a676ae804b69017a8bd979f6401582a51b31e5b9353fa8beb

test:
  secret_key_base: 185b788185325dc3d1313c4ea05088dea1db905412e7aa898d2b3cde9d28f466a038037ab4ab6bdff5dd41af264924b890f61310181f220ad15fc1b59d31240c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
